= Adoptium(R) Secure Supply Chain Management
:description: Adoptium Secure Supply Chain Management
:keywords: Security SSDF SLSA Supply Chain
:orgname: Eclipse Adoptium
:lang: en
:page-authors: tellison

== Adoptium and SLSA Levels

The Supply chain Levels for Software Artifacts (SLSA) is a security framework that helps to provide confidence that a set of inputs such as source code, libraries, and software packages, led to a set of well-defined outputs suchas as a binary and software bill of materials. It is a tool to help a producer trust the part of the supply chain you directly control and helps provide confidence in your build process catching any upstream supply chain attack.

Adoptium has evaluated the secure engineering practices of the project to determine the appropriate SLSA level attestation. Our evaluation is provided in a Github issue, and we have achieved the following requirements:

=== SLSA Level One - **Completed**

Build - https://slsa.dev/spec/v0.1/requirements#scripted-build[Scripted build^]::
+
All build steps for Eclipse Temurin are defined in build scripts stored in the 
https://github.com/adoptium/temurin-build[adoptium/temurin-build^]
repository and invoked by
https://ci.adoptopenjdk.net/[our continuous build system^]. The build scripts are available for anyone to view and reuse, with the documentation in the repository
https://github.com/adoptium/temurin-build#readme[readme file^].

Provenence - https://slsa.dev/spec/v0.1/requirements#available[Available^]::
+
WARNING: The provenance description of Eclipse Temurin available to the consumer in a format that the consumer accepts. The format SHOULD be in-toto SLSA Provenance, but another format MAY be used if both producer and consumer agree and it meets all the other requirements.


=== SLSA Level Two - **Completed**

Source - https://slsa.dev/spec/v0.1/requirements#version-controlled[Version controlled^]::
+
Adoptium mirrors the OpenJDK sources in our local Github repository (e.g. https://github.com/adoptium/jdk17u[adoptium/jdk17u^]). Every change to the source we build and scripts we use is tracked by the Github version control system. This ensures a record of the history of changes that went into each revision. Each change contains the identities of the uploader and reviewers, timestamps of the reviews and submission, the change description/justification, the content of the change, and the parent revisions.
+
Each immutable revision has a unique reference with an indefinite lifespan via Github using the {repo URL + branch/tag/ref + commit ID}.


Build - https://slsa.dev/spec/v0.1/requirements#build-service[Build service^]::
+
All Adoptium's build steps run on
https://ci.adoptopenjdk.net/[our own managed build service^], not on a developer’s workstation. Access to the build service is carefully managed by the project.

Provenance - https://slsa.dev/spec/v0.1/requirements#authenticated[Authenticated^]::
+
WARNING: The provenance’s authenticity and integrity can be verified by the consumer. This SHOULD be through a digital signature from a private key accessible only to the service generating the provenance.

Provenance - https://slsa.dev/spec/v0.1/requirements#service-generated[Service generated^]::
+
All of Adoptium provenance data is generated directly by the project continuous build and test systems. Service users cannot injject or alter the contents of the provenance. Eclipse Temurin's code signatures are generated by the Eclipse code-signing service, other provenance data including the software bill of materials, cryptographic hashes, build metadata, etc. is directly emitted by the project build system


SLSA Level Three - **In progress** ::
* [x] Source - Retained 18mo.
* [x] Build - Build as code
* Build - Ephemeral environment
* [x] Build - Isolated
* Provenance - Non-falsifiable

SLSA Level Four - **In progress** ::
* Source - Two-person reviewed
* Build - Parameterless
* Build - Hermetic
* [x] Build - Reproducible
* [x] Provenance - Dependencies complete
* Common - Security
* Common - Access
* Common - Superusers
